"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.namesArray = void 0;
exports.namesArray = ["Wajeeha", "Masooma", "Fajar", "Maneeha", "Javaria", "Zoha", "Anaya", "Zainab", "Anooshay", "Areeba", "Masvera"];
// console.log(namesArray[0], namesArray[1], namesArray[2], namesArray[3], namesArray[4]);
// console.log(namesArray[0]);
// console.log(namesArray[1]);
// console.log(namesArray[2]);
// console.log(namesArray[3]);
// console.log(namesArray[4]);
